# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_d', '0002_auto_20170925_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdmodel',
            name='uploads',
            field=models.FileField(upload_to='model/', verbose_name='上传文件'),
        ),
    ]
