# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_d', '0003_auto_20170925_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='模型名字')),
                ('upload_obj', models.FileField(upload_to='model/obj', verbose_name='上传obj文件')),
                ('upload_pic', models.FileField(upload_to='model/obj', verbose_name='上传pic文件')),
                ('upload_mtl', models.FileField(upload_to='model/obj', verbose_name='上传mtl文件')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='tdmodel',
            name='uploads',
            field=models.FileField(upload_to='model/ply', verbose_name='上传文件'),
        ),
    ]
